/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Korab Gashi
 */
public class PhonebookApp extends javax.swing.JFrame {

    /**
     * Creates new form PhonebookApp
     */
    public PhonebookApp() throws SQLException {
        initComponents();
        TregoTabelen();
    }
    
    public Connection getConnection(){
        Connection databaza;
        try{
            databaza = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook", "root", "Prishtina123..");
            return databaza;
        }catch (Exception e){
            e.printStackTrace();
            return null;
        }
    }
    
    public ArrayList<Phonebook> getPhonebookList() throws SQLException{
        ArrayList<Phonebook> phonebookList = new ArrayList();
        Connection connection = getConnection();
        String query = "SELECT * FROM `phonebook_table`";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Phonebook phonebook;
            while(rs.next()){
                phonebook = new Phonebook(rs.getInt("ID"), rs.getString("Emri"), rs.getString("Mbiemri"), rs.getInt("Telefoni"), rs.getString("Titulli"));
                phonebookList.add(phonebook);
            }
        }catch (Exception er){
            er.printStackTrace();
        }
        return phonebookList;
        
    }
    
    public void TregoTabelen() throws SQLException{
        ArrayList<Phonebook> lista = getPhonebookList();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[5];
        for (int rreshti = 0; rreshti < lista.size(); rreshti++){
            row[0] = lista.get(rreshti).getId();
            row[1] = lista.get(rreshti).getEmri();
            row[2] = lista.get(rreshti).getMbiemri();
            row[3] = lista.get(rreshti).getTelefoni();
            row[4] = lista.get(rreshti).getTitulli();
            
            dtm.addRow(row);
        }
        
        
    }
    
    public void excecuteSQlQuery(String query, String message) throws SQLException{
        Connection con = getConnection();
        Statement st;
        
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) == 1){
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                TregoTabelen();
                
                JOptionPane.showMessageDialog(null, "Te dhenat jane " +message+ "me Sukses!");
            }else
                JOptionPane.showMessageDialog(null,"Te dhenat nuk jane shtuar" +message);
        }catch (Exception er){
            er.printStackTrace();
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_emri = new javax.swing.JTextField();
        jTextField_mbiemri = new javax.swing.JTextField();
        jTextField_telefoni = new javax.swing.JTextField();
        jTextField_titulli = new javax.swing.JTextField();
        jButton_shto = new javax.swing.JButton();
        jButton_edito = new javax.swing.JButton();
        jButton_fshije = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Emri", "Mbiemri", "Telefoni", "Titulli"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Emri");

        jLabel2.setText("Mbiemri");

        jLabel3.setText("Telefoni");

        jLabel4.setText("Titulli");

        jTextField_emri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emriActionPerformed(evt);
            }
        });

        jButton_shto.setText("Shto");
        jButton_shto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_shtoMouseClicked(evt);
            }
        });

        jButton_edito.setText("Edito");
        jButton_edito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_editoMouseClicked(evt);
            }
        });

        jButton_fshije.setText("Fshije");
        jButton_fshije.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_fshijeMouseClicked(evt);
            }
        });

        jLabel5.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_shto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_edito, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_fshije, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_mbiemri, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addComponent(jTextField_telefoni)
                                .addComponent(jTextField_titulli)
                                .addComponent(jTextField_emri)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_emri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_telefoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_titulli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_shto)
                    .addComponent(jButton_edito)
                    .addComponent(jButton_fshije)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_emriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emriActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel tm = jTable1.getModel();
        jTextField_id.setText(tm.getValueAt(i, 0).toString());
        jTextField_emri.setText(tm.getValueAt(i, 1).toString());
        jTextField_mbiemri.setText(tm.getValueAt(i, 2).toString());
        jTextField_telefoni.setText(tm.getValueAt(i, 3).toString());
        jTextField_titulli.setText(tm.getValueAt(i, 4).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_editoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_editoMouseClicked
        String query = "UPDATE `phonebook_table` SET `emri`='"+jTextField_emri.getText()+"',`mbiemri`='"+jTextField_mbiemri.getText()+"',`telefoni`='"+jTextField_telefoni.getText()+"',`titulli`='"+jTextField_titulli.getText()+"' WHERE `ID` ="+jTextField_id.getText();
        try{
            excecuteSQlQuery(query, "edituar ");
        }catch (SQLException ex){
            Logger.getLogger(Phonebook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_editoMouseClicked

    private void jButton_shtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_shtoMouseClicked
        String query = "INSERT INTO `phonebook_table` (`emri`,`mbiemri`,`telefoni`,`titulli`) VALUES ('"+jTextField_emri.getText()+"','"+jTextField_mbiemri.getText()+"','"+jTextField_telefoni.getText()+"','"+jTextField_titulli.getText()+"')";
        try{
            excecuteSQlQuery(query, "shtuar ");
        }catch (SQLException ex){
            Logger.getLogger(Phonebook.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jButton_shtoMouseClicked

    private void jButton_fshijeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_fshijeMouseClicked
        String query = "DELETE FROM `phonebook_table` WHERE ID = "+jTextField_id.getText();
        try{
            excecuteSQlQuery(query,"fshire ");
        }catch (SQLException ex){
            Logger.getLogger(Phonebook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_fshijeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhonebookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhonebookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhonebookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhonebookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PhonebookApp().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PhonebookApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_edito;
    private javax.swing.JButton jButton_fshije;
    private javax.swing.JButton jButton_shto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_emri;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_mbiemri;
    private javax.swing.JTextField jTextField_telefoni;
    private javax.swing.JTextField jTextField_titulli;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
